#------------------------------------------------#
#                ¡The Hub Plugin!                #
#             ¡Configuration Files!              #
#        The plugin accept the color codes:      #
#                                                #
#           &1 = Dark Blue | &2 = Dark Green     #
#           &3 = Dark Aqua | &4 = Dark Red       #
#           &5 = Purple    | &6 = Gold           #
#           &7 = Gray      | &8 = Dark Gray      #
#           &9 = Blue      | &0 = Black          #
#           &a = Green     | &b = Aqua           #
#           &c = Red       | &d = Pink           #
#           &e = Yellow    | &f = White          #
#           &r = Reset     | &l = BOLD           #
#           &k = Magic     | &o = Italic         #
#                                                # 
#           Thanks for use my plugin! ;)         #
#            Hub 3.9 by DJBiokinetix             #
#                                                #
#          Visit my server of Minecraft          #
#            IP: mc.playcraftsv.com              #
#                                                #
#     Remember: Stop the music with command      #
#                  /stopmusic                    #
#------------------------------------------------#

#---------[Join and Leave]---------
Join: '&8[&6Hub&8] &e%user%&8» &7join the game'
Leave: '&8[&6Hub&8] &e%user%&8» &7left the game'
#---------[Command message]--------
E Fake: '&8[&6Hub&8] &e%user%&8» &7join the game'
S Fake: '&8[&6Hub&8] &e%user%&8» &7left the game'
#------------[Firework]------------
Time: 15
Firework message: '&8[&6Hub&8] &7Launch firework!'
No permission: '&8[&6Hub&8] &cNo permissions!'
Incorrect usage: '&8[&6Hub&8] &7Incorrect command! usage: &b/fw'
Wait message: '&8[&6Hub&8] &7Wait &c%time &7seconds for launch other firework!'
#-----------------------------------------------------------------------------------------#
#¡¡¡WARNING!!! Don't touch or change the variable "%user% and %time" or the plugin crash! #
#-----------------------------------------------------------------------------------------#
